# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 735301fcfbfbe49a2466bfc477a4d6cd0c76b116c26bccb4df3613304fd7113905bf58bcd5373de9a84424bc50d8f74c9aed5d12d36c2de41a556d0c2ee746d4

test:
  secret_key_base: f499874b07dfdd10d9352eb6f1724334526a7ff1c038e997a55b45e4a8623a6aa866d11aca85ea2e104d27f215572ad99b8b22d3772e3fca46957e3328ec26dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
